name: file_ext
description: Helper methods for filesystem-, path- and stdin-related manipulations.
version: 0.7.3
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/file_ext/

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  async: ^2.11.0
  file: ^7.0.0
  glob: ^2.1.1
  loop_visitor: ^0.4.0
  path: ^1.8.3

dev_dependencies:
  intl: ^0.19.0
  lints: ^3.0.0
  parse_args: ^0.13.0
  test: ^1.23.1
  thin_logger: ^0.2.0
