name: file_ext
description: Extension methods for filesystem-related manipulations.
version: 0.1.0
homepage: https://github.com/aiurovet/file_ext/

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  file: ^6.1.2
  glob: ^2.0.2

dev_dependencies:
  intl: ^0.17.0
  lints: ^1.0.0
  parse_args: ^0.7.1
  test: ^1.16.0
  thin_logger: ^0.1.3
