name: file_ext
description: Extension methods for filesystem-related manipulations.
version: 0.2.0
homepage: https://github.com/aiurovet/file_ext/

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  async: ^2.10.0
  file: ^6.1.4
  glob: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  intl: ^0.18.0
  lints: ^2.0.1
  parse_args: ^0.11.1
  test: ^1.16.0
  thin_logger: ^0.2.0
