name: file_ext
description: Helper methods for filesystem-, path- and stdin-related manipulations.
version: 0.6.1
homepage: https://github.com/aiurovet/file_ext/

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  async: ^2.11.0
  file: ^6.1.4
  glob: ^2.1.1
  loop_visitor: ^0.3.0
  path: ^1.8.3

dev_dependencies:
  intl: ^0.18.0
  lints: ^2.0.1
  parse_args: ^0.13.0
  test: ^1.23.1
  thin_logger: ^0.2.0
